version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: quicktasks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: quicktasks
    ports:
      - "5432:5432"
    volumes:
      - quicktasks-postgres-data:/var/lib/postgresql/data

volumes:
  quicktasks-postgres-data:
